### ISSUE TITLE
您好想问下这个会长期维护吗？我可以拿来使用吗

### ISSUE THREAD

**Issue by xiaoshengwpp** [levi-Ma/preset-uni-vue3#1]

**Comment by levi-Ma** [comment]
跟着uni-app官方的脚手架更新，大概一周会更新1到2次这种

**Comment by xiaoshengwpp** [comment]
> uni-app官方的脚手架更新，大概一周跟着会更新1到2次这种

了解，方便的话能更新下 apis文件下的index.ts 中的定义和使用 事例吗。刚开始用ts 这里有点没看明白。
<img width="374" alt="image" src="https://user-images.githubusercontent.com/27839112/170825368-b23cd3d7-7071-4b5f-9886-5a152b29e667.png">
后续定义接口的时候不清楚是否是这样使用。感谢

**Comment by levi-Ma** [comment]
> > uni-app官方的手架更新，大概一周跟着脚会更新1到2次这种
> 
> 刚开始用的时候可以用下面的api来定义和使用文件。 <img alt="图片" width="374" src="https://user-images.githubusercontent.com/27839112/170825368-b23cd3d7-7071-4b5f-9886-5a152b29e667.png">

已添加
