### ISSUE TITLE
这个可以发布成小程序吗

### ISSUE THREAD

**Issue by weiveFf** [levi-Ma/preset-uni-vue3#3]

**Comment by levi-Ma** [comment]
现阶段微信小程序上的工作较多，但基于uni-app的话，其他小程序只要按照规范去做，理论上没问题；代码中没有单独对某个小程序做限制

**Comment by weiveFf** [comment]
我用小程序进行编译 成了这个
![image](https://user-images.githubusercontent.com/73087960/232672614-0f71b686-5bd2-4acb-b541-3e4efcaa0c62.png)

需要配置什么呢 或者是什么问题呢

**Comment by levi-Ma** [comment]
能把文件发一下吗

**Comment by levi-Ma** [comment]
报错信息说多了一个双引号，你看看代码

**Comment by weiveFf** [comment]
我的代码之前发布在H5，现在要小程序跑起来，我看看问题把先
